### ISSUE TITLE
Table adds horizontal scrolling on mobile browser window

### ISSUE THREAD

**Issue by arothuis** [rjkip/2021-resident-visa-data#1]
Not sure if intentional, but the table adds horizontal scrolling to the entire browser window on mobile.

This can probably be fixed by adding the following to `ProcessingTable.svelte` but this may have some accessibility issues (a wrapper might be needed).

```css
table {
    display: block;
    overflow-x: auto;
    white-space: nowrap;
}
```
